sudo: required
services:
  - docker

before_install:
  - docker build -t advortco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run advortco/react-test npm test -- --coverage

after_success:
  - docker build -t advortco/multi-client ./client
  - docker build -t advortco/multi-nginx ./nginx
  - docker build -t advortco/multi-server ./server
  - docker build -t advortco/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push advortco/multi-client
  - docker push advortco/multi-nginx
  - docker push advortco/multi-server
  - docker push advortco/multi-worker
